---
abstract: 'A Map/Reduce implementation for Alg:Dep graphs'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.48
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Algorithm::Dependency::MapReduce
name: Algorithm-Dependency-MapReduce
no_index:
  directory:
    - inc
    - t
requires:
  Algorithm::Dependency: 1.108
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
